### ISSUE TITLE
Cluster Registration

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multi-cluster-traffic-controller#44]
**What**

We want to be able to register clusters with the control plane within a given tenant NS . These clusters will be represented by secrets. These cluster secrets will be the place where additional information and context is added about the cluster. 

The setup of this can be done via a script initially. 

This should also spit our yaml for the sync agent and webhook configuration

**Constraints**

There isn't a requirement to setup a the tenant as part of this work, this is just focused on registering the cluster within a tenant.

- [ ] #68
- [ ] Add logic to the registration script that uses a KUBECONFIG to create a new service account and create a rolebinding in the tenant ns
- [ ] Add logic that uses the SA and outputs a deployment etc to setup the syncer

**Comment by maleck13** [comment]
@philbrookes is there specific things you see as needed for the sync agent deployment yaml?

**Comment by philbrookes** [comment]
I'd say this is a good starting point: https://github.com/Kuadrant/multi-cluster-traffic-controller/tree/main/config/agent

It's what is used to deploy the current ingress-agent to a cluster.
