### ISSUE TITLE
Add support for reconciling Gateway Listeners

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multi-cluster-traffic-controller#46]
**What**

The gateway controller in the traffic controller, will need to reconcile the listeners defined in the gateway. For each listener the following requirements have been identified

- Check if the host is part of a managed zone for that tenant
- If not then it can be ignored
- ensure there is a certificate for the host specified (if it is a wildcard host the cert should be a wildcard cert)
- ensure there is a DNSRecord based on the LB status in the gateway (only once the certificate is ready)

**Comment by david-martin** [comment]
@maleck13 is this different from #53

**Comment by maleck13** [comment]
No but I guess this one has more info? so close 53?

**Comment by david-martin** [comment]
Agreed
