### ISSUE TITLE
Allow use of shared managed zones

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multi-cluster-traffic-controller#65]
**What**

When setting up traffic controller, it should be possible to setup a default zone that is used by default for hosts in gateways etc. 

**Use Case**
I don't want to have to setup a zone for every tenant ns but instead want to define a default zone that can be used by any tenant. Each tenant should receive a subdomain underneath the root domain of this zone

**Option**

Allow zones to be added to the same namespace as the traffic controller. By default these zones are considered shared. When a new namespace is added with a specific label, the controller should assign that new tenant a subdomain of the default zone. <tenant>.<zone>

**Comment by maleck13** [comment]
@mikenairn is this completed as part of the MZ PRs?

**Comment by mikenairn** [comment]
@maleck13 Yes i would say so. The controller looks for a MZ in the it's own NS, if none exists in the tenant NS.
